name: Public Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest

    steps:
      # 标准签出
      - name: Checkout target repo
        uses: actions/checkout@v4
# 如果上游仓库有对.github/workflows/下的文件进行变更，则需要使用有workflow权限的token
        with:
          token: ${{ secrets.ACTION_TOKEN }}
   
      # 获取分支名
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      # 运行同步动作
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: movie-web/movie-web
          upstream_sync_branch: ${{ env.BRANCH_NAME }}
          target_sync_branch: ${{ env.BRANCH_NAME }}
          target_repo_token: ${{ secrets.ACTION_TOKEN }}
          upstream_pull_args: --allow-unrelated-histories --no-edit 
          shallow_since: '1 days ago'
          test_mode: false
